### PR TITLE
fix: Race condition on quickly setting and getting config

### LINKED ISSUE #187: C++ client: race condition when calling setConfiguration and getCurrentConfiguration from callbacks
I have an application where I want to call `getCurrentConfiguration` and `setConfiguration` from (different) callbacks. These may be called at arbitrary times, in arbitrary order. I'm running with a normal (single threaded) spinner. 

The problem can be understood like this:
 - One callback calls `setConfiguration` on the client. This resets the `received_configuration_` flag to `false`.
 - The server responds to the service, and by sending the updated parameters on the `parameter_updates` topic. The client has a callback on this topic, which will be put in the callback queue. This will set the `received_configuration_` flag to `true` again.
 - A second callback calls `getCurrentConfiguration` on the client. This blocks until the `received_configuration_` flag is set to `true`. 

The thread may now be blocked, depending on whether the `parameter_updates` message is put first or second in the callback queue.

### PR DESCRIPTION
**Pull request by rokusottervanger**
fixes #187 by using the server's response to the set service to update the latest configuration.

### CODE REVIEW

**Comment by gbiggs** [comment]
Can you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that can be used to test this PR fixes the problem?

**Comment by gbiggs** [comment]
Thanks for the test, which I got to fail without the fix and pass with the fix. Thanks also for the contribution!

**Comment by rokusottervanger** [comment]
I need this fix on a ROS Melodic system as well. Should I make a new PR backporting this fix? What is the best way forward?

**Comment by gbiggs** [comment]
We'll handle backporting to melodic.

**Pull request merged**
