### PR TITLE
support float('inf') for cfg file

### PR DESCRIPTION
**Pull request by knorth55**
This PR supports `float('inf')` and `-float('inf')` for `dynamic_reconfigure` `cfg` file.
This feature is supported in `parameter_generator.py` but not in `parameter_generator_catkin.py`.
https://github.com/ros/dynamic_reconfigure/blob/noetic-devel/src/dynamic_reconfigure/parameter_generator.py#L419-L425

I also add `double_inf` and `double_negative_inf` for test build.

cc. @sktometometo

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by knorth55** [comment]
I change this PR target to `noetic-devel` branch.

**Comment by knorth55** [comment]
this PR is useful for `inf` setting in `cfg` file.
can anyone please review and merge this PR?

**Comment by knorth55** [comment]
can anyone please review and merge this PR?

**Comment by knorth55** [comment]
kindly ping. can anyone review and merge this PR?

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
Thanks for the contribution!

**Pull request merged**
